### ISSUE TITLE
Cannot find RepairTasks.exe or other files needed

### ISSUE THREAD

**Issue by eggraves2** [Dijji/RepairTasks#13]
Hey not sure if i am just using Github wrong or what, but I download the zip but it is named RepairTasks-master (master node for the code) but inside there are no exe's if you could help me that would be great. Also your walkthrough discusses another file needed for windows 7 but links back to the other repo that no longer has the files. Thanks again.

**Comment by Dijji** [comment]
On the home page, click on ‘Release’ on the lower set of tabs, the one that goes commits, then branch, then release.

This will take you to a page where you can download all the zip files contain released code. The download on the front page just gives you a zip file of the sources.

Dijji

**Comment by eggraves2** [comment]
Thank you I feel dumb but that showed me the way!
